### ISSUE TITLE
CentOS 7 中使用的是 这个依赖 cppzmq-devel

### ISSUE THREAD

**Issue by fbzl** [fifilyu/CommandBridge#1]

**Comment by fifilyu** [comment]
项目 `CMake` 中没有处理外部的 `zmq` 包依赖，需要用户自行安装发行版相应的包。

确实如你所说，`CentOS7` 中需要安装包 `cppzmq-devel`

**Comment by fbzl** [comment]
server.cxx 文件中 97行

```
// 父进程自动忽略子进程的状态，防止出现僵死的子进程
signal (SIGCHLD, SIG_IGN);
```

这样执行 python 程序 supervisor 等报错

```
IOError: [Errno 10] No child processes
```

我改为如下可以使用了

```
signal (SIGCHLD, SIG_DFL);
```

**Comment by fifilyu** [comment]
直接修改信号虽然能运行，但忽略了僵死子进程的问题。
能否提供一下你的supervisor配置以及运行时具体的报错信息，用于测试。
简单的python程序我测试是成功的。

**Comment by fbzl** [comment]
supervisor 配置

```
[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10 
loglevel=info 
pidfile=/tmp/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket

; 以上为默认配置中未注释内容

[program:pyspider]
command=python /usr/bin/pyspider
directory=/root/
startsecs=0
stopwaitsecs=0
autostart=false
autorestart=false
user=root
stdout_logfile=/data/wwwlogs/pyspider.log
stderr_logfile=/data/wwwlogs/pyspider.err
```

运行

```
/usr/local/cmdbr/bin/cmdbr-cli -h 127.0.0.1 -p 44357 -a "supervisorctl status"
```

PS: 服务端 `c` 参数修改为可以为空值 

报错信息

```
Traceback (most recent call last):
  File "/usr/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2700, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2717, in _compute_dependencies
    from _markerlib import compile as compile_marker
  File "/usr/lib/python2.7/site-packages/_markerlib/__init__.py", line 3, in <module>
    from _markerlib.markers import default_environment, compile, interpret
  File "/usr/lib/python2.7/site-packages/_markerlib/markers.py", line 46, in <module>
    'platform.version': platform.version(),
  File "/usr/lib64/python2.7/platform.py", line 1338, in version
    return uname()[3]
  File "/usr/lib64/python2.7/platform.py", line 1277, in uname
    processor = _syscmd_uname('-p','')
  File "/usr/lib64/python2.7/platform.py", line 1012, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] No child processes
```

系统信息

```
Linux localhost 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
